---
- name: Install required packages
  apt: 
    update_cache: yes
    state: latest
    pkg:
      - python-apt
      - python3-apt
      - git
      - build-essential
      - cmake
      - unzip
      - zip
      - gcc
      - make
      - openssl
      - libssl-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - python-dev
      - python3-dev
      - python-pip
      - python3-pip
      - gcc
      - vim
      - aptitude
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - zsh
      - tmux
  when: ansible_os_family == "Debian"
